"""
Initial AHU dynamic modeling baseline.

This script uses only the Python standard library. It builds one-step-ahead
models from the preprocessed 5-minute AHU data:

  x(t) -> target(t+h)

The purpose is to establish a reproducible first benchmark before moving to
larger data-driven models or an RL surrogate environment.
"""

from __future__ import annotations

import argparse
import csv
import math
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path


FEATURE_COLUMNS = [
    "T_out",
    "T_ret",
    "T_rec",
    "T_coil",
    "T_sup",
    "pressure_hex",
    "u_heat",
    "u_heat_recovery",
    "u_FF1",
]

TARGET_COLUMNS = [
    "T_rec",
    "T_sup",
    "T_coil",
    "pressure_hex",
]


@dataclass
class Dataset:
    timestamps: list[str]
    features: list[list[float]]
    current_values: dict[str, list[float]]
    targets: dict[str, list[float]]
    feature_names: list[str]


@dataclass
class LinearModel:
    target: str
    weights: list[float]
    feature_means: list[float]
    feature_stds: list[float]
    feature_names: list[str]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train initial AHU dynamic baseline models.")
    parser.add_argument(
        "--input",
        default="data_preprocessing/preprocess/ahu_model_5min.csv",
        help="Model-ready CSV generated by preprocess_ahu_data.py.",
    )
    parser.add_argument("--out-dir", default="model_outputs", help="Directory for reports and predictions.")
    parser.add_argument("--freq-min", type=int, default=5, help="Expected interval between rows.")
    parser.add_argument(
        "--horizons",
        default="1,3,6,12",
        help="Comma-separated prediction horizons in time steps. With 5-min data: 1,3,6,12 = 5,15,30,60 min.",
    )
    parser.add_argument("--ridge-alpha", type=float, default=1.0, help="L2 regularization strength.")
    return parser.parse_args()


def to_float(value: str) -> float:
    if value == "":
        raise ValueError("empty value")
    return float(value)


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def time_features(timestamp: datetime) -> list[float]:
    minute_of_day = timestamp.hour * 60 + timestamp.minute
    day_angle = 2.0 * math.pi * minute_of_day / (24.0 * 60.0)
    year_day = timestamp.timetuple().tm_yday
    year_angle = 2.0 * math.pi * year_day / 365.25
    return [
        math.sin(day_angle),
        math.cos(day_angle),
        math.sin(year_angle),
        math.cos(year_angle),
    ]


def parse_horizons(text: str) -> list[int]:
    horizons = [int(part.strip()) for part in text.split(",") if part.strip()]
    if not horizons or any(horizon <= 0 for horizon in horizons):
        raise ValueError("--horizons must contain positive integers")
    return horizons


def build_dataset(rows: list[dict[str, str]], freq_min: int, horizon_steps: int) -> Dataset:
    expected_step = timedelta(minutes=freq_min * horizon_steps)
    feature_names = FEATURE_COLUMNS + ["hour_sin", "hour_cos", "year_sin", "year_cos"]

    timestamps: list[str] = []
    features: list[list[float]] = []
    current_values = {target: [] for target in TARGET_COLUMNS}
    targets = {target: [] for target in TARGET_COLUMNS}

    parsed_times = [datetime.fromisoformat(row["timestamp"]) for row in rows]

    for idx in range(len(rows) - horizon_steps):
        current = rows[idx]
        nxt = rows[idx + horizon_steps]
        if parsed_times[idx + horizon_steps] - parsed_times[idx] != expected_step:
            continue

        try:
            base_features = [to_float(current[col]) for col in FEATURE_COLUMNS]
            next_targets = {target: to_float(nxt[target]) for target in TARGET_COLUMNS}
            now_targets = {target: to_float(current[target]) for target in TARGET_COLUMNS}
        except ValueError:
            continue

        timestamps.append(nxt["timestamp"])
        features.append(base_features + time_features(parsed_times[idx]))
        for target in TARGET_COLUMNS:
            current_values[target].append(now_targets[target])
            targets[target].append(next_targets[target])

    return Dataset(timestamps, features, current_values, targets, feature_names)


def split_indexes(n_rows: int) -> tuple[range, range, range]:
    train_end = int(n_rows * 0.70)
    val_end = int(n_rows * 0.85)
    return range(0, train_end), range(train_end, val_end), range(val_end, n_rows)


def fit_scaler(features: list[list[float]], indexes: range) -> tuple[list[float], list[float]]:
    n_features = len(features[0])
    means = []
    stds = []
    for col in range(n_features):
        values = [features[idx][col] for idx in indexes]
        mean = sum(values) / len(values)
        variance = sum((value - mean) ** 2 for value in values) / max(1, len(values) - 1)
        std = math.sqrt(variance)
        means.append(mean)
        stds.append(std if std > 1e-12 else 1.0)
    return means, stds


def scaled_row(row: list[float], means: list[float], stds: list[float]) -> list[float]:
    return [(value - mean) / std for value, mean, std in zip(row, means, stds)]


def solve_linear_system(matrix: list[list[float]], vector: list[float]) -> list[float]:
    n = len(vector)
    augmented = [matrix[i][:] + [vector[i]] for i in range(n)]

    for col in range(n):
        pivot = max(range(col, n), key=lambda row: abs(augmented[row][col]))
        if abs(augmented[pivot][col]) < 1e-12:
            raise ValueError("singular matrix")
        if pivot != col:
            augmented[col], augmented[pivot] = augmented[pivot], augmented[col]

        pivot_value = augmented[col][col]
        for j in range(col, n + 1):
            augmented[col][j] /= pivot_value

        for row in range(n):
            if row == col:
                continue
            factor = augmented[row][col]
            if factor == 0:
                continue
            for j in range(col, n + 1):
                augmented[row][j] -= factor * augmented[col][j]

    return [augmented[i][n] for i in range(n)]


def train_ridge(
    dataset: Dataset, target: str, indexes: range, alpha: float
) -> LinearModel:
    means, stds = fit_scaler(dataset.features, indexes)
    n_features = len(dataset.feature_names) + 1  # intercept
    xtx = [[0.0 for _ in range(n_features)] for _ in range(n_features)]
    xty = [0.0 for _ in range(n_features)]

    for idx in indexes:
        x = [1.0] + scaled_row(dataset.features[idx], means, stds)
        y = dataset.targets[target][idx]
        for i in range(n_features):
            xty[i] += x[i] * y
            for j in range(n_features):
                xtx[i][j] += x[i] * x[j]

    for i in range(1, n_features):
        xtx[i][i] += alpha

    weights = solve_linear_system(xtx, xty)
    return LinearModel(target, weights, means, stds, ["intercept"] + dataset.feature_names)


def predict(model: LinearModel, raw_features: list[float]) -> float:
    x = [1.0] + scaled_row(raw_features, model.feature_means, model.feature_stds)
    return sum(weight * value for weight, value in zip(model.weights, x))


def metrics(y_true: list[float], y_pred: list[float]) -> dict[str, float]:
    n = len(y_true)
    errors = [pred - true for true, pred in zip(y_true, y_pred)]
    mae = sum(abs(err) for err in errors) / n
    rmse = math.sqrt(sum(err * err for err in errors) / n)
    mean_y = sum(y_true) / n
    sse = sum(err * err for err in errors)
    sst = sum((true - mean_y) ** 2 for true in y_true)
    r2 = 1.0 - sse / sst if sst > 0 else float("nan")
    bias = sum(errors) / n
    return {"n": float(n), "mae": mae, "rmse": rmse, "r2": r2, "bias": bias}


def evaluate_model(
    dataset: Dataset, model: LinearModel, target: str, indexes: range
) -> dict[str, float]:
    y_true = [dataset.targets[target][idx] for idx in indexes]
    y_pred = [predict(model, dataset.features[idx]) for idx in indexes]
    return metrics(y_true, y_pred)


def evaluate_persistence(dataset: Dataset, target: str, indexes: range) -> dict[str, float]:
    y_true = [dataset.targets[target][idx] for idx in indexes]
    y_pred = [dataset.current_values[target][idx] for idx in indexes]
    return metrics(y_true, y_pred)


def top_coefficients(model: LinearModel, limit: int = 8) -> list[tuple[str, float]]:
    pairs = list(zip(model.feature_names, model.weights))
    non_intercept = [pair for pair in pairs if pair[0] != "intercept"]
    return sorted(non_intercept, key=lambda pair: abs(pair[1]), reverse=True)[:limit]


def write_predictions(
    path: Path,
    dataset: Dataset,
    models: dict[str, LinearModel],
    indexes: range,
) -> None:
    columns = ["timestamp"]
    for target in TARGET_COLUMNS:
        columns.extend([f"{target}_true", f"{target}_persistence", f"{target}_linear"])

    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=columns)
        writer.writeheader()
        for idx in indexes:
            row = {"timestamp": dataset.timestamps[idx]}
            for target in TARGET_COLUMNS:
                row[f"{target}_true"] = f"{dataset.targets[target][idx]:.6g}"
                row[f"{target}_persistence"] = f"{dataset.current_values[target][idx]:.6g}"
                row[f"{target}_linear"] = f"{predict(models[target], dataset.features[idx]):.6g}"
            writer.writerow(row)


def format_metric_row(name: str, values: dict[str, float]) -> str:
    return (
        f"{name:13s} n={int(values['n']):6d} "
        f"MAE={values['mae']:.4f} RMSE={values['rmse']:.4f} "
        f"R2={values['r2']:.4f} bias={values['bias']:.4f}"
    )


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = load_rows(input_path)
    horizons = parse_horizons(args.horizons)
    report_lines: list[str] = []
    report_lines.append("AHU initial dynamic modeling report")
    report_lines.append(f"Input: {input_path.resolve()}")
    report_lines.append(f"Generated at: {datetime.now().isoformat(timespec='seconds')}")
    report_lines.append(f"Expected interval: {args.freq_min} min")
    report_lines.append(f"Horizons: {', '.join(str(h) for h in horizons)} steps")
    report_lines.append("")

    first_prediction_written = False
    for horizon_steps in horizons:
        dataset = build_dataset(rows, args.freq_min, horizon_steps)
        if len(dataset.features) < 100:
            raise RuntimeError(f"Not enough samples for horizon {horizon_steps}.")

        train_idx, val_idx, test_idx = split_indexes(len(dataset.features))
        split_map = {"train": train_idx, "val": val_idx, "test": test_idx}
        models: dict[str, LinearModel] = {}

        report_lines.append(
            f"Horizon: {horizon_steps} steps ({horizon_steps * args.freq_min} min)"
        )
        report_lines.append(f"Consecutive samples: {len(dataset.features)}")
        report_lines.append(
            f"Splits: train={len(train_idx)}, val={len(val_idx)}, test={len(test_idx)}"
        )
        report_lines.append(f"Feature columns: {', '.join(dataset.feature_names)}")
        report_lines.append("")

        for target in TARGET_COLUMNS:
            model = train_ridge(dataset, target, train_idx, args.ridge_alpha)
            models[target] = model

            report_lines.append(f"Target: {target}(t+{horizon_steps})")
            for split_name, indexes in split_map.items():
                persistence = evaluate_persistence(dataset, target, indexes)
                linear = evaluate_model(dataset, model, target, indexes)
                report_lines.append(format_metric_row(f"{split_name}/persist", persistence))
                report_lines.append(format_metric_row(f"{split_name}/linear", linear))
            report_lines.append("Top standardized linear coefficients:")
            for name, coefficient in top_coefficients(model):
                report_lines.append(f"  {name:16s} {coefficient: .6f}")
            report_lines.append("")

        if not first_prediction_written:
            prediction_path = out_dir / "ahu_baseline_test_predictions_horizon_5min.csv"
            write_predictions(prediction_path, dataset, models, test_idx)
            first_prediction_written = True

        summary_lines = [f"Test summary for horizon {horizon_steps * args.freq_min} min:"]
        for split_name, indexes in split_map.items():
            if split_name != "test":
                continue
            for target in TARGET_COLUMNS:
                persistence = evaluate_persistence(dataset, target, indexes)
                linear = evaluate_model(dataset, models[target], target, indexes)
                delta = persistence["rmse"] - linear["rmse"]
                summary_lines.append(
                    f"  {target}: persistence RMSE={persistence['rmse']:.4f}, "
                    f"linear RMSE={linear['rmse']:.4f}, improvement={delta:.4f}"
                )
        print("\n".join(summary_lines))

    report_path = out_dir / "ahu_baseline_model_report.txt"
    report_path.write_text("\n".join(report_lines), encoding="utf-8")

    print(f"Wrote {report_path}")
    print(f"Wrote {out_dir / 'ahu_baseline_test_predictions_horizon_5min.csv'}")


if __name__ == "__main__":
    main()
