"""
Create an interactive standalone HTML visualization for the two-stage AHU models.

The page reads ahu_two_stage_test_predictions_5min.csv and writes a zoomable
Canvas-based HTML report with value plots, error plots, and metric tables.
"""

from __future__ import annotations

import argparse
import csv
import html
import json
import math
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


TARGETS = ("T_rec", "T_sup")
VALUE_SERIES = ("true", "ridge_arx", "tree_ensemble")
ERROR_SERIES = ("ridge_arx", "tree_ensemble")
COLORS = {
    "true": "#111827",
    "ridge_arx": "#2563eb",
    "tree_ensemble": "#dc2626",
}
LABELS = {
    "true": "True",
    "ridge_arx": "Linear regression",
    "tree_ensemble": "Tree model",
}


@dataclass(frozen=True)
class Metrics:
    mae: float
    rmse: float
    bias: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Visualize AHU two-stage prediction results.")
    parser.add_argument(
        "--input",
        default="model_outputs/ahu_two_stage_test_predictions_5min.csv",
        help="Prediction CSV generated by model_ahu_two_stage.py.",
    )
    parser.add_argument(
        "--output",
        default="model_outputs/ahu_two_stage_predictions_5min.html",
        help="Output standalone HTML file.",
    )
    parser.add_argument(
        "--max-points",
        type=int,
        default=0,
        help="Maximum plotted points after uniform downsampling. Use 0 to plot all rows.",
    )
    parser.add_argument("--horizon-min", type=int, default=5, help="Prediction horizon shown in the HTML title.")
    return parser.parse_args()


def read_predictions(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    if not rows:
        raise ValueError(f"No rows found in {path}")
    return rows


def downsample_rows(rows: list[dict[str, str]], max_points: int) -> list[dict[str, str]]:
    if max_points <= 0 or len(rows) <= max_points:
        return rows
    step = math.ceil(len(rows) / max_points)
    sampled = rows[::step]
    if sampled[-1] is not rows[-1]:
        sampled.append(rows[-1])
    return sampled


def to_float(value: str) -> float:
    return float(value)


def compute_metrics(rows: list[dict[str, str]], target: str, prediction: str) -> Metrics:
    errors = [
        to_float(row[f"{target}_{prediction}"]) - to_float(row[f"{target}_true"])
        for row in rows
    ]
    mae = sum(abs(error) for error in errors) / len(errors)
    rmse = math.sqrt(sum(error * error for error in errors) / len(errors))
    bias = sum(errors) / len(errors)
    return Metrics(mae=mae, rmse=rmse, bias=bias)


def nice_time_label(text: str) -> str:
    return datetime.fromisoformat(text).strftime("%Y-%m-%d %H:%M")


def build_plot_data(rows: list[dict[str, str]]) -> dict[str, object]:
    targets: dict[str, object] = {}
    for target in TARGETS:
        true = [to_float(row[f"{target}_true"]) for row in rows]
        value_series = {
            series: [to_float(row[f"{target}_{series}"]) for row in rows]
            for series in VALUE_SERIES
        }
        error_series = {
            series: [
                to_float(row[f"{target}_{series}"]) - true[idx]
                for idx, row in enumerate(rows)
            ]
            for series in ERROR_SERIES
        }
        targets[target] = {"values": value_series, "errors": error_series}

    return {
        "timestamps": [row["timestamp"] for row in rows],
        "targets": targets,
        "valueSeries": list(VALUE_SERIES),
        "errorSeries": list(ERROR_SERIES),
        "colors": COLORS,
        "labels": LABELS,
        "expectedStepMinutes": 5,
    }


def render_metric_explanation() -> str:
    return """
    <section class="note">
      <b>Metric meaning:</b>
      MAE is the average absolute prediction error, so lower is better and the unit is degC.
      RMSE is the square-root mean squared error; it penalizes large mistakes more than MAE.
      Bias is the average signed error, prediction minus true value; positive means overprediction,
      negative means underprediction.
    </section>
    """


def render_metrics_table(rows: list[dict[str, str]]) -> str:
    body = []
    for target in TARGETS:
        for series in ERROR_SERIES:
            m = compute_metrics(rows, target, series)
            body.append(
                "<tr>"
                f"<td>{html.escape(target)}</td>"
                f"<td>{html.escape(LABELS[series])}</td>"
                f"<td>{m.mae:.4f}</td>"
                f"<td>{m.rmse:.4f}</td>"
                f"<td>{m.bias:.4f}</td>"
                "</tr>"
            )
    return f"""
    <table>
      <thead>
        <tr>
          <th>Target</th>
          <th>Model</th>
          <th>MAE</th>
          <th>RMSE</th>
          <th>Bias</th>
        </tr>
      </thead>
      <tbody>{''.join(body)}</tbody>
    </table>
    """


def render_chart(target: str, kind: str, title: str, subtitle: str) -> str:
    key = f"{target}_{kind}"
    return f"""
    <section class="panel">
      <div class="panel-head">
        <div>
          <div class="panel-title">{html.escape(title)}</div>
          <div class="window-label" data-window="{html.escape(key)}">{html.escape(subtitle)}</div>
        </div>
        <div class="tools">
          <button type="button" data-action="zoom-in" data-target="{html.escape(key)}">Zoom in</button>
          <button type="button" data-action="zoom-out" data-target="{html.escape(key)}">Zoom out</button>
          <button type="button" data-action="reset" data-target="{html.escape(key)}">Reset</button>
        </div>
      </div>
      <canvas data-chart="{html.escape(key)}" data-target-name="{html.escape(target)}" data-kind="{html.escape(kind)}" height="360"></canvas>
      <div class="readout" data-readout="{html.escape(key)}"></div>
    </section>
    """


def render_target_section(target: str) -> str:
    return f"""
    <h2>{html.escape(target)}</h2>
    {render_chart(target, "values", f"{target} value prediction", "Drag to pan, use mouse wheel or buttons to zoom.")}
    {render_chart(target, "errors", f"{target} prediction error", "Error = prediction - true. This view separates curves that overlap in the value plot.")}
    """


def render_script(plot_data: dict[str, object]) -> str:
    data_json = json.dumps(plot_data, separators=(",", ":")).replace("</", "<\\/")
    return f"""
  <script>
    const AHU_DATA = {data_json};
    const charts = new Map();

    function clamp(value, min, max) {{
      return Math.max(min, Math.min(max, value));
    }}

    function formatTimestamp(text) {{
      return text.slice(0, 16);
    }}

    function minutesBetween(left, right) {{
      const leftTime = Date.parse(left.replace(" ", "T"));
      const rightTime = Date.parse(right.replace(" ", "T"));
      return (rightTime - leftTime) / 60000;
    }}

    function isContinuous(prevIndex, index) {{
      if (prevIndex === null || index <= 0) return true;
      const minutes = minutesBetween(AHU_DATA.timestamps[prevIndex], AHU_DATA.timestamps[index]);
      return Math.abs(minutes - AHU_DATA.expectedStepMinutes) < 1e-6;
    }}

    function makeChart(canvas) {{
      const key = canvas.dataset.chart;
      const n = AHU_DATA.timestamps.length;
      return {{
        key,
        canvas,
        ctx: canvas.getContext("2d"),
        target: canvas.dataset.targetName,
        kind: canvas.dataset.kind,
        start: 0,
        end: n - 1,
        hoverIndex: null,
        dragging: false,
        dragStartX: 0,
        dragStartStart: 0,
        dragStartEnd: n - 1,
        cssWidth: 0,
        cssHeight: 0,
      }};
    }}

    function seriesList(chart) {{
      return chart.kind === "values" ? AHU_DATA.valueSeries : AHU_DATA.errorSeries;
    }}

    function seriesValues(chart) {{
      return AHU_DATA.targets[chart.target][chart.kind];
    }}

    function chartArea(chart) {{
      return {{left: 66, top: 22, width: chart.cssWidth - 90, height: chart.cssHeight - 74}};
    }}

    function visibleBounds(chart) {{
      const values = seriesValues(chart);
      const left = Math.max(0, Math.floor(chart.start));
      const right = Math.min(AHU_DATA.timestamps.length - 1, Math.ceil(chart.end));
      let min = chart.kind === "errors" ? 0 : Infinity;
      let max = chart.kind === "errors" ? 0 : -Infinity;
      for (const series of seriesList(chart)) {{
        const arr = values[series];
        for (let i = left; i <= right; i++) {{
          const v = arr[i];
          if (v < min) min = v;
          if (v > max) max = v;
        }}
      }}
      if (!Number.isFinite(min) || !Number.isFinite(max)) {{
        min = -1;
        max = 1;
      }}
      const margin = (max - min) * 0.10 || 0.1;
      return {{min: min - margin, max: max + margin}};
    }}

    function resizeCanvas(chart) {{
      const rect = chart.canvas.getBoundingClientRect();
      const dpr = window.devicePixelRatio || 1;
      const width = Math.max(320, Math.floor(rect.width));
      const height = Number(chart.canvas.getAttribute("height")) || 360;
      chart.canvas.width = Math.floor(width * dpr);
      chart.canvas.height = Math.floor(height * dpr);
      chart.ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      chart.cssWidth = width;
      chart.cssHeight = height;
    }}

    function xForIndex(chart, index, area) {{
      const span = chart.end - chart.start || 1;
      return area.left + ((index - chart.start) / span) * area.width;
    }}

    function indexForX(chart, x, area) {{
      return chart.start + ((x - area.left) / area.width) * (chart.end - chart.start);
    }}

    function yForValue(value, area, bounds) {{
      const span = bounds.max - bounds.min || 1;
      return area.top + area.height - ((value - bounds.min) / span) * area.height;
    }}

    function drawLine(ctx, chart, arr, area, bounds, color, width, dash) {{
      ctx.save();
      ctx.strokeStyle = color;
      ctx.lineWidth = width;
      ctx.setLineDash(dash || []);
      ctx.beginPath();
      const left = Math.max(0, Math.floor(chart.start));
      const right = Math.min(AHU_DATA.timestamps.length - 1, Math.ceil(chart.end));
      let started = false;
      let prevIndex = null;
      for (let i = left; i <= right; i++) {{
        const x = xForIndex(chart, i, area);
        const y = yForValue(arr[i], area, bounds);
        if (!started || !isContinuous(prevIndex, i)) {{
          ctx.moveTo(x, y);
          started = true;
        }} else {{
          ctx.lineTo(x, y);
        }}
        prevIndex = i;
      }}
      ctx.stroke();
      ctx.restore();
    }}

    function drawChart(chart) {{
      const ctx = chart.ctx;
      const width = chart.cssWidth;
      const height = chart.cssHeight;
      if (!width || !height) return;

      const area = chartArea(chart);
      const bounds = visibleBounds(chart);
      ctx.clearRect(0, 0, width, height);
      ctx.fillStyle = "#ffffff";
      ctx.fillRect(0, 0, width, height);

      ctx.strokeStyle = "#e5e7eb";
      ctx.lineWidth = 1;
      ctx.fillStyle = "#6b7280";
      ctx.font = "12px Arial";
      ctx.textAlign = "right";
      ctx.textBaseline = "middle";
      for (let tick = 0; tick <= 4; tick++) {{
        const value = bounds.min + (bounds.max - bounds.min) * tick / 4;
        const y = yForValue(value, area, bounds);
        ctx.beginPath();
        ctx.moveTo(area.left, y);
        ctx.lineTo(area.left + area.width, y);
        ctx.stroke();
        ctx.fillText(value.toFixed(chart.kind === "errors" ? 3 : 2), area.left - 8, y);
      }}

      if (chart.kind === "errors") {{
        const zeroY = yForValue(0, area, bounds);
        ctx.save();
        ctx.strokeStyle = "#111827";
        ctx.setLineDash([5, 5]);
        ctx.beginPath();
        ctx.moveTo(area.left, zeroY);
        ctx.lineTo(area.left + area.width, zeroY);
        ctx.stroke();
        ctx.restore();
      }}
      const values = seriesValues(chart);
      for (const series of seriesList(chart)) {{
        const dash = series === "persistence" ? [5, 4] : [];
        const lineWidth = series === "true" ? 1.7 : 1.4;
        drawLine(ctx, chart, values[series], area, bounds, AHU_DATA.colors[series], lineWidth, dash);
      }}

      ctx.strokeStyle = "#9ca3af";
      ctx.strokeRect(area.left, area.top, area.width, area.height);

      const leftIndex = Math.max(0, Math.round(chart.start));
      const rightIndex = Math.min(AHU_DATA.timestamps.length - 1, Math.round(chart.end));
      ctx.fillStyle = "#6b7280";
      ctx.textAlign = "left";
      ctx.textBaseline = "top";
      ctx.fillText(formatTimestamp(AHU_DATA.timestamps[leftIndex]), area.left, area.top + area.height + 12);
      ctx.textAlign = "right";
      ctx.fillText(formatTimestamp(AHU_DATA.timestamps[rightIndex]), area.left + area.width, area.top + area.height + 12);

      if (chart.hoverIndex !== null) {{
        const i = clamp(chart.hoverIndex, leftIndex, rightIndex);
        const x = xForIndex(chart, i, area);
        ctx.strokeStyle = "#374151";
        ctx.beginPath();
        ctx.moveTo(x, area.top);
        ctx.lineTo(x, area.top + area.height);
        ctx.stroke();
        const parts = [formatTimestamp(AHU_DATA.timestamps[i])];
        for (const series of seriesList(chart)) {{
          parts.push(`${{AHU_DATA.labels[series]}}=${{values[series][i].toFixed(chart.kind === "errors" ? 4 : 3)}}`);
        }}
        const readout = document.querySelector(`[data-readout="${{chart.key}}"]`);
        if (readout) readout.textContent = parts.join(" | ");
      }}

      const label = document.querySelector(`[data-window="${{chart.key}}"]`);
      if (label) {{
        label.textContent = `${{formatTimestamp(AHU_DATA.timestamps[leftIndex])}} to ${{formatTimestamp(AHU_DATA.timestamps[rightIndex])}} (${{rightIndex - leftIndex + 1}} points)`;
      }}
    }}

    function zoom(chart, centerIndex, factor) {{
      const n = AHU_DATA.timestamps.length;
      const oldSpan = chart.end - chart.start;
      const newSpan = clamp(oldSpan * factor, 20, n - 1);
      let start = centerIndex - newSpan / 2;
      let end = centerIndex + newSpan / 2;
      if (start < 0) {{
        end -= start;
        start = 0;
      }}
      if (end > n - 1) {{
        start -= end - (n - 1);
        end = n - 1;
      }}
      chart.start = clamp(start, 0, n - 1);
      chart.end = clamp(end, 0, n - 1);
      drawChart(chart);
    }}

    function resetChart(chart) {{
      chart.start = 0;
      chart.end = AHU_DATA.timestamps.length - 1;
      drawChart(chart);
    }}

    function attachEvents(chart) {{
      chart.canvas.addEventListener("wheel", (event) => {{
        event.preventDefault();
        const rect = chart.canvas.getBoundingClientRect();
        const area = chartArea(chart);
        const x = event.clientX - rect.left;
        const center = clamp(indexForX(chart, x, area), 0, AHU_DATA.timestamps.length - 1);
        zoom(chart, center, event.deltaY < 0 ? 0.75 : 1.35);
      }}, {{passive: false}});

      chart.canvas.addEventListener("pointerdown", (event) => {{
        chart.dragging = true;
        chart.dragStartX = event.clientX;
        chart.dragStartStart = chart.start;
        chart.dragStartEnd = chart.end;
        chart.canvas.setPointerCapture(event.pointerId);
      }});

      chart.canvas.addEventListener("pointermove", (event) => {{
        const rect = chart.canvas.getBoundingClientRect();
        const area = chartArea(chart);
        const x = event.clientX - rect.left;
        if (chart.dragging) {{
          const dx = event.clientX - chart.dragStartX;
          const span = chart.dragStartEnd - chart.dragStartStart;
          const shift = -dx / area.width * span;
          chart.start = chart.dragStartStart + shift;
          chart.end = chart.dragStartEnd + shift;
          if (chart.start < 0) {{
            chart.end -= chart.start;
            chart.start = 0;
          }}
          if (chart.end > AHU_DATA.timestamps.length - 1) {{
            chart.start -= chart.end - (AHU_DATA.timestamps.length - 1);
            chart.end = AHU_DATA.timestamps.length - 1;
          }}
        }}
        const nextHover = clamp(Math.round(indexForX(chart, x, area)), 0, AHU_DATA.timestamps.length - 1);
        if (chart.dragging || nextHover !== chart.hoverIndex) {{
          chart.hoverIndex = nextHover;
          drawChart(chart);
        }}
      }});

      chart.canvas.addEventListener("pointerup", (event) => {{
        chart.dragging = false;
        if (chart.canvas.hasPointerCapture(event.pointerId)) {{
          chart.canvas.releasePointerCapture(event.pointerId);
        }}
      }});

      chart.canvas.addEventListener("pointerleave", () => {{
        chart.dragging = false;
        chart.hoverIndex = null;
        const readout = document.querySelector(`[data-readout="${{chart.key}}"]`);
        if (readout) readout.textContent = "";
        drawChart(chart);
      }});

      chart.canvas.addEventListener("dblclick", () => resetChart(chart));
    }}

    function init() {{
      document.querySelectorAll("canvas[data-chart]").forEach((canvas) => {{
        const chart = makeChart(canvas);
        charts.set(chart.key, chart);
        attachEvents(chart);
        resizeCanvas(chart);
        drawChart(chart);
      }});

      document.querySelectorAll("button[data-action]").forEach((button) => {{
        button.addEventListener("click", () => {{
          const chart = charts.get(button.dataset.target);
          if (!chart) return;
          const center = (chart.start + chart.end) / 2;
          if (button.dataset.action === "zoom-in") zoom(chart, center, 0.5);
          if (button.dataset.action === "zoom-out") zoom(chart, center, 2.0);
          if (button.dataset.action === "reset") resetChart(chart);
        }});
      }});

      window.addEventListener("resize", () => {{
        for (const chart of charts.values()) {{
          resizeCanvas(chart);
          drawChart(chart);
        }}
      }});
    }}

    init();
  </script>
"""


def render_html(
    input_path: Path,
    rows: list[dict[str, str]],
    plotted_rows: list[dict[str, str]],
    horizon_min: int = 5,
) -> str:
    first = nice_time_label(rows[0]["timestamp"])
    last = nice_time_label(rows[-1]["timestamp"])
    generated = datetime.now().strftime("%Y-%m-%d %H:%M")
    sections = "\n".join(render_target_section(target) for target in TARGETS)
    plot_data = build_plot_data(plotted_rows)
    legend_items = "\n".join(
        f'<span class="legend-item"><span class="swatch" style="background:{COLORS[series]}"></span>{html.escape(LABELS[series])}</span>'
        for series in VALUE_SERIES
    )

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>AHU Two-Stage {horizon_min}-Minute Prediction Results</title>
  <style>
    :root {{
      color-scheme: light;
      font-family: Arial, Helvetica, sans-serif;
      background: #f3f4f6;
      color: #111827;
    }}
    body {{ margin: 0; padding: 28px; }}
    main {{ max-width: 1120px; margin: 0 auto; }}
    h1 {{ margin: 0 0 8px; font-size: 28px; font-weight: 700; }}
    h2 {{ margin: 28px 0 8px; font-size: 21px; }}
    .meta, .note {{
      color: #4b5563;
      line-height: 1.5;
      font-size: 14px;
    }}
    .meta {{ margin: 0 0 18px; }}
    .note {{
      background: #ffffff;
      border: 1px solid #d1d5db;
      border-radius: 8px;
      padding: 12px 14px;
      margin: 0 0 14px;
    }}
    .legend {{
      display: flex;
      gap: 18px;
      align-items: center;
      margin: 0 0 18px;
      font-size: 14px;
      flex-wrap: wrap;
    }}
    .legend-item {{ display: inline-flex; align-items: center; gap: 7px; }}
    .swatch {{ width: 28px; height: 3px; border-radius: 999px; display: inline-block; }}
    .panel {{
      background: #ffffff;
      border: 1px solid #d1d5db;
      border-radius: 8px;
      margin: 14px 0;
      padding: 14px 16px 12px;
    }}
    .panel-head {{
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 12px;
      margin-bottom: 8px;
    }}
    .panel-title {{ font-size: 16px; font-weight: 700; }}
    .window-label {{ color: #6b7280; font-size: 12px; margin-top: 3px; }}
    .tools {{ display: flex; gap: 6px; flex-wrap: wrap; justify-content: flex-end; }}
    button {{
      border: 1px solid #cbd5e1;
      background: #ffffff;
      color: #111827;
      border-radius: 6px;
      padding: 6px 9px;
      font-size: 12px;
      cursor: pointer;
    }}
    button:hover {{ background: #f3f4f6; }}
    canvas {{
      width: 100%;
      height: 360px;
      display: block;
      border: 1px solid #e5e7eb;
      cursor: grab;
      touch-action: none;
    }}
    canvas:active {{ cursor: grabbing; }}
    .readout {{
      min-height: 18px;
      margin-top: 8px;
      color: #374151;
      font-size: 13px;
      font-variant-numeric: tabular-nums;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
      background: #ffffff;
      border: 1px solid #d1d5db;
      border-radius: 8px;
      overflow: hidden;
      font-size: 14px;
      margin-bottom: 18px;
    }}
    th, td {{
      padding: 10px 12px;
      border-bottom: 1px solid #e5e7eb;
      text-align: right;
      white-space: nowrap;
    }}
    th:first-child, td:first-child, th:nth-child(2), td:nth-child(2) {{ text-align: left; }}
    th {{ background: #f9fafb; font-weight: 700; }}
    tr:last-child td {{ border-bottom: none; }}
  </style>
</head>
<body>
  <main>
    <h1>AHU Two-Stage {horizon_min}-Minute Prediction Results</h1>
    <p class="meta">
      Source: {html.escape(str(input_path))}<br />
      Time range: {html.escape(first)} to {html.escape(last)}.
      Rows: {len(rows)}; plotted rows: {len(plotted_rows)}.
      Generated: {html.escape(generated)}.
    </p>
    <div class="legend">{legend_items}</div>
    {render_metric_explanation()}
    {render_metrics_table(rows)}
    {sections}
  </main>
{render_script(plot_data)}
</body>
</html>
"""


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)
    rows = read_predictions(input_path)
    plotted_rows = downsample_rows(rows, args.max_points)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_html(input_path, rows, plotted_rows, args.horizon_min), encoding="utf-8")
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
